name: OpenOSRS - Code convention

on: [pull_request, push]

jobs:
  checkstyle:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      - name: Assembling
        run: gradlew assemble --console=plain
      - name: Checking code conventions
        run: gradlew checkstyleMain --console=plain