name: OpenOSRS - Pull Request

on: pull_request

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest

    steps:
      - name: Assign author to PR
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-lint:
    runs-on: ubuntu-latest

    steps:
      - name: PR title lint
        if: github.event_name == 'pull_request'
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '^\w+: \w+'

  triage:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Labeler
        continue-on-error: true
        uses: actions/labeler@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}