name: OpenOSRS - Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest

    steps:
      - name: Assign author to PR
        if: github.event.action == 'opened'
        uses: technote-space/assign-author@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}